services:
  bot:
    build: .
    container_name: senzi-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
